#!/bin/bash

#SBATCH --container-image projects.cispa.saarland:5005\#c01jixu/prog:24.03-py3
#SBATCH --container-mounts=/home/c01jixu/CISPA-home/tmp:/tmp
#SBATCH --container-workdir=/home/c01jixu/CISPA-home/ProG
#SBATCH --gres=gpu:A100:1
#SBATCH --partition tmp
#SBATCH --output=/home/c01jixu/CISPA-scratch/c01jixu/job-%j.out
#SBATCH --time=10:00:00
#SBATCH --job-name=Downstream_D3

pwd

JOBDATADIR=/home/"$USER"/CISPA-home/"$USER"/job-"$SLURM_JOB_ID"/

mkdir -p $JOBDATADIR
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCN --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GAT.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GAT --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GIN.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GIN --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphSAGE.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphSAGE --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GCov.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GCov --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/GraphCL.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type All-in-one --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type GPF --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
python3 downstream_task.py --pre_train_model_path ./Experiment/pre_trained_model/Actor/SimGRACE.GraphTransformer.128hidden_dim.pth --task NodeTask --dataset_name Actor --gnn_type GraphTransformer --prompt_type GPF-plus --shot_num 10 --hid_dim 128 --num_layer 2 --lr 1e-3 --decay 2e-6 --seed 0 --epochs 100
mv /home/c01jixu/CISPA-scratch/c01jixu/job-$SLURM_JOB_ID.out $JOBDATADIR/out.txt